###

# curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type:
#application/json" -X POST http://localhost:8085/auftraege
POST http://localhost:8085/auftraege
Content-Type: application/json

{
  "key1": "value1",
  "key2": "value2"
}

###

