apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    env: production
spec:
  containers:
    - name: simple-webapp-mysql
      image: kodekloud/simple-webapp-mysql
      envFrom:
        - secretRef:
            name: db-secret
