apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: http-server
      labels:
        tier: frontend
    spec:
      containers:
        - name: httpd-alpine
          image: httpd:2.4-alpine
  replicas: 3