apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  securityContext:
    runAsUser: 1001
  containers:
  -  image: ubuntu
     name: web
     command: ["sleep", "5000"]
     securityContext:
      runAsUser: 1002   # starts as user 1002
  -  image: kodekloud/filebeat-configured
     name: sidecar      # starts as user 1001
     command: ["sleep", "5000"]
     volumeMounts: 
     - mountPath: /var/log/event-simulator/
       name: log-volume