apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice-job
spec:
  template:
    spec:
      containers:
      - name: throw-dice-job-container
        image: kodekloud/throw-dice
      restartPolicy: Never
  completions: 3
  parallelism: 3
  backoffLimit: 15
